#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4  # 1
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    enable_os_fileformat_icon = true
    lint_on_the_fly = true
    lint_on_save = true
    default_indent = 4
    relativenumber = false
    enable_cursorline = false
    guifont = 'DejaVu Sans Mono for Powerline 14'
    statusline_right_sections = ['fileformat', 'cursorpos', 'percentage', 'date', 'time']

    bootstrap_before = "myspacevim#before"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
